services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    command: >
      postgres
      -c shared_buffers=256MB
      -c work_mem=4MB
      -c maintenance_work_mem=64MB
      -c max_connections=100
      -c effective_cache_size=512MB
      -c wal_level=minimal
      -c synchronous_commit=off
      -c checkpoint_timeout=15min
      -c default_statistics_target=100
      -c max_wal_senders=0
    volumes:
      - pg_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '1280M'

  pgbouncer_transaction:
    image: edoburu/pgbouncer:v1.24.1-p1
    container_name: pgbouncer_transaction
    restart: unless-stopped
    ports:
      - "6432:6432"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      PGBOUNCER_USER: postgres
      PGBOUNCER_PASSWORD: postgres
      POOL_MODE: transaction
      MAX_CLIENT_CONN: 10
      DEFAULT_POOL_SIZE: 5
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '128M'

  pgbouncer_session:
    image: edoburu/pgbouncer:v1.24.1-p1
    container_name: pgbouncer_session
    restart: unless-stopped
    ports:
      - "6433:6432"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      PGBOUNCER_USER: postgres
      PGBOUNCER_PASSWORD: postgres
      POOL_MODE: session
      MAX_CLIENT_CONN: 10
      DEFAULT_POOL_SIZE: 5
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '128M'

volumes:
  pg_data: